export enum DiagnosticoCardiometabolico {
  HIPERTENSION_ARTERIAL = 'HIPERTENSION_ARTERIAL',
  DIABETES_MELLITUS_TIPO_2 = 'DIABETES_MELLITUS_TIPO_2',
  DISLIPIDEMIA = 'DISLIPIDEMIA',
  OBESIDAD = 'OBESIDAD',
}

export enum EstadoControlCondicion {
  CONTROLADA = 'CONTROLADA',
  NO_CONTROLADA = 'NO_CONTROLADA',
  NO_VALORABLE = 'NO_VALORABLE',
}

export enum GradoObesidad {
  SOBREPESO = 'SOBREPESO',
  OBESIDAD_I = 'OBESIDAD_I',
  OBESIDAD_II = 'OBESIDAD_II',
  OBESIDAD_III = 'OBESIDAD_III',
}
